name: Wiki_Contribute
on:
  push: 
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: WikiリポジトリをClone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://shimajima-eiji:${GITHUB_TOKEN}@github.com/shimajima-eiji/__Github-Operation.wiki

      - name: pushのためのconfig
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "shimajima-eiji"
          
      # commitに失敗した場合は、wikiを更新しなかった可能性が高い
      - name: Commit files
        run: |
          git push --mirror https://shimajima-eiji:${PERSONAL_ACCESS_TOKEN}@github.com/shimajima-eiji/____Github-Operation_wiki.git
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
